# application.yml

server:
  port: 9090
  tomcat:
    connection-timeout: 300000
    max-http-header-size: 65536
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  application:
    name: face-detection-services

  profiles:
    active: kloudspot

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/face_detection_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:SIVA@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mongodb:
    uri: mongodb://localhost:27017/camera_recording_face_detection

  codec:
    max-in-memory-size: 10MB

jwt:
  secret: face_detection_super_secret_key_12345678901234567890
  expiration: 86400000
logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG
    com:
      stations:
        facedetection:
          integration:
            kloudspot: DEBUG
pattern:
   console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
