# application.yml

server:
  port: 9090
  tomcat:
    connection-timeout: 300000
    max-http-header-size: 65536
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  application:
    name: face-detection-services

  profiles:
    active: kloudspot

  datasource:
    url: jdbc:mysql://zdotapps-devenviron.cvuouqwaej9d.ap-south-1.rds.amazonaws.com:3306/3C_faceDetection_App_DB
    username: zda_devenviron
    password: 7XxqiZw391vCIl6MudTk

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mongodb:
    uri: mongodb://localhost:27017/camera_recording_face_detection

  codec:
    max-in-memory-size: 10MB

jwt:
  secret: face_detection_super_secret_key_12345678901234567890
  expiration: 86400000
logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG
    org:
      springframework:
        web:
          reactive:
            function:
              client: DEBUG
    com:
      stations:
        facedetection:
          integration:
            kloudspot: DEBUG
pattern:
   console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"